substitutions:
  run_time: 1min
  sleep_time: 20min

esphome:
  name: epd47-1
  friendly_name: epd47-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret epd_key

ota:
  password: !secret epd_pass

wifi:
  power_save_mode: none
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi2_ssid
    password: !secret wifi2_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${friendly_name} FAP'
    password: !secret appass

captive_portal:
   

external_components:
  - source:
      type: git
      url: https://github.com/vbaksa/esphome
      ref: dev
    components:
      - lilygo_t5_47_battery 
      - lilygo_t5_47_display

time:
  - platform: homeassistant
    id: ntp

switch:
  - platform: restart
    name: '${friendly_name} Restart'

# display
font:
  - file: 'fonts/IBMPlexMono-Bold.ttf'
    id: din_big
    glyphs: "+-0123456789.:"
    size: 300
  - file: 'fonts/IBMPlexMono-Bold.ttf'
    id: din_med
    size: 100

display:
  - platform: lilygo_t5_47_display
    rotation: 0
    update_interval: 60s
    full_update_every: 5
    lambda: |-
      
      it.strftime(15, 310, id(din_big), TextAlign::BASELINE_LEFT, "%H:%M", id(ntp).now());
      it.strftime(50, 500, id(din_med), TextAlign::BASELINE_LEFT, "%Y-%m-%d %a", id(ntp).now());
